apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wallabag
resources:
  - namespace.yaml
  - deployment.yaml
  - networking.yaml
  - secrets.yaml
  - database.yaml
  - configmap.yaml
  - cloudflare.yaml
