apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-app-secrets
  namespace: wallabag
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: wallabag-db-password
    - secretKey: SYMFONY__ENV__DATABASE_PASSWORD
      remoteRef:
        key: wallabag-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-db-creds
  namespace: wallabag
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: wallabag-db-username
    - secretKey: password
      remoteRef:
        key: wallabag-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-cloudflare-tunnel-token
  namespace: wallabag
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: wallabag-cloudflare-tunnel-token
