apiVersion: v1
kind: Service
metadata:
  name: wallabag
  namespace: wallabag
spec:
  selector:
    app: wallabag
  type: ClusterIP
  ports:
    - name: wallabag
      port: 3004
      targetPort: 80
