apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-pat-token
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: homelab-renovate-github-pat-token
