# Pod address allocation delegated to each node in the cluster
ipam:
  mode: kubernetes



# ~~~~~ L2 Announcements configuration ~~~~~~~~~~

# Ensures kube-proxy pod does not run
kubeProxyReplacement: true

# Tells Cilium where the API server is
# kube-proxy generates the kubernetes service, but it is disabled
k8sServiceHost: 192.168.0.101
k8sServicePort: 6443

# eBPF config - k3s already mounts cgroup at /sys/fs/cgroup
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup


# API chatter is increased when Cilium runs under L2 Announcements mode
# Limiting the API rate limit avoids introducing throttling
k8sClientRateLimit:
  qps: 20
  burst: 20

# Loadbalancer IPs are generated as a VIP tied to the node
# If a node goes down, Cilium elects another ndoe to host that VIP
# Nodes "announce" to the LAN:
# "If you want to reach IP <loadbalancerIP>, then come to my MAC!"
l2Announcements:
  enabled: true


# Extras
ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

