apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store-homelab
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://bde-dev-kv-homelab.vault.azure.net/
      tenantId: dd114501-3212-46b0-9b66-2f8e0bf94f22
      authSecretRef:
        clientId:
          name: azure-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: ClientSecret
          namespace: external-secrets
