apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-prod-cnpg-v2
spec:
  instances: 1

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: commafeed-database
      network-policy-type: database

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: commafeed-db-barman-store

  externalClusters:
    - name: clusterBackup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: commafeed-db-barman-store
          serverName: commafeed-db-prod-cnpg-v1

  bootstrap:
    recovery:
      source: clusterBackup

  storage:
    size: 1Gi

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: commafeed-db
            spec:
              type: ClusterIP
