apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-retain
  resources:
    requests:
      storage: 1Gi
