apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls
  dnsNames:
    - harbor.bde-dev.net
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
