apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor

spec:
  interval: 15m
  chart:
    spec:
      chart: harbor
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor

  valuesFrom:
    - kind: ConfigMap
      name: harbor-values
