apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secrets
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: harbor-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-cloudflare-tunnel-token
  namespace: harbor
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: harbor-cloudflare-tunnel-token
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: harbor-registry-creds
spec:
  externalSecretName: harbor-registry-creds

  namespaceSelectors:
    - matchLabels:
        harbor-pull-secret: "enabled"

  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      name: azure-kv-store-homelab
      kind: ClusterSecretStore

    refreshInterval: 1h

    target:
      name: harbor-registry-creds
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "harbor.bde-dev.net": {
                  "username": "{{ .HARBOR_ADMIN_USERNAME }}",
                  "password": "{{ .HARBOR_ADMIN_PASSWORD }}",
                  "auth": "{{ printf "%s:%s" .HARBOR_ADMIN_USERNAME .HARBOR_ADMIN_PASSWORD | b64enc }}"
                }
              }
            }

    data:
      - secretKey: HARBOR_ADMIN_USERNAME
        remoteRef:
          key: harbor-admin-username
      - secretKey: HARBOR_ADMIN_PASSWORD
        remoteRef:
          key: harbor-admin-password
