apiVersion: apps/v1
kind: Deployment
metadata:
  name: stm-cloudflared
  namespace: mealie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stm-cloudflared
  template:
    metadata:
      labels:
        app: stm-cloudflared
        network-policy-type: cloudflared
    spec:
      imagePullSecrets:
        - name: harbor-registry-creds
      containers:
        - image: docker.io/cloudflare/cloudflared:2025.11.1
          name: stm-cloudflared
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: social-to-mealie-cloudflare-tunnel-token
                  key: token
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --loglevel
            - debug
            - --metrics
            - 0.0.0.0:2000
            - run

          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
