apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: social-to-mealie-app-secrets
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: MEALIE_API_KEY
      remoteRef:
        key: mealie-api-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: social-to-mealie-cloudflare-tunnel-token
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: social-to-mealie-cloudflare-tunnel-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: social-to-mealie-openai-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: mealie-openai-api-key
