apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-username
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
