apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-prod-cnpg-v1
spec:
  instances: 1

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: linkding-database
      network-policy-type: database

  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding-db-creds

  storage:
    size: 1Gi
    storageClass: synology-iscsi-retain

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: linkding-db
            spec:
              type: ClusterIP
