apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-prod-cnpg-v1
spec:
  instances: 1

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding-db-secrets

  storage:
    size: 1Gi

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: linkding-db
            spec:
              type: ClusterIP
