apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    email: brad.evans0925@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
      - dns01:
        cloudflare:
          email: brad.evans0925@gmail.com
          apiTokenSecretRef:
            name: cloudflare-dns-api-token
            key: cloudflare-dns-api-token
