apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-homelab
    kind: ClusterSecretStore
  data:
    - secretKey: cloudflare-dns-api-token
      remoteRef:
        key: cloudflare-dns-api-token
